'''
A digital safe requires a secret key generated by combining two user ID numbers. Write a program that reads two space-separated integers representing these IDs. Output the result of applying the bitwise AND operator to these two numbers. Input Format: A single line containing two space-separated integers. Output Format: A single integer representing the bitwise AND result.
'''
a,b = input().split()
a,b = int(a),int(b)
print(a&b)
